// Generated by @nuxtjs/sitemap

declare module 'nitropack' {
  interface PrerenderRoute {
    _sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
    'sitemap:sources': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapSourcesHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.0_h3@1.15.3_magicast@0.3.5_vite@6.3.5_@types+node@24.0.1_jiti@2.4.2_4d01b957d3a85bae1f9442bd7e1d82d8/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
    }
}

export {}
